Nimbus / Pan-M dataset plot notebooks
angelolab/publications pull request #4
Opened 2024-05-22 18:21 UTC by JLrumberger

**What is the purpose of this PR?**

Adding the code for producing the plots for our upcoming paper.

**Remaining issues**

None

2024-05-22 18:38 UTC, ngreenwald requested changes
Looks good, just the right level of description in the readme.

Figure 2 plotting notebook has the figure panels in kind of a confusing order, is this because the code for earlier panels depends on the later panels?

2024-05-22 18:38 UTC, ngreenwald commented on 2024-Rumberger_etal_Nimbus/README.md
> +# Code for Rumberger et al., Improving cell phenotyping by factoring in spatial marker expression patterns with Nimbus
```suggestion
# Code for Rumberger, Greenwald et al., Improving cell phenotyping by factoring in spatial marker expression patterns with Nimbus
```

2024-05-22 18:38 UTC, ngreenwald commented on 2024-Rumberger_etal_Nimbus/README.md
> +# Code for Rumberger et al., Improving cell phenotyping by factoring in spatial marker expression patterns with Nimbus
Same for folder name please :)

2024-05-23 12:17 UTC, JLrumberger commented
I reordered the figure 2 plotting notebook, now it's more organized (b-f, then the overlay images a, g-i) and corrected the foldername / readme. I'll close this branch and open a new one, because I can't work on this repository locally. A few files in `2022-McCaffrey_etal_HumanTB` cause errors when cloning the repo. I tried downloading it as .zip, and then adding this repo as origin to the local repo, but I still got errors.

2024-05-23 12:17 UTC, closed without merging